#!/bin/bash

BUILD_TYPE=$1
CMAKEDIR=$2
ASSERTIONS=$3

cmake -G Ninja \
    -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
    -DLLVM_ENABLE_PROJECTS='clang;lld' \
    -DLLVM_ENABLE_RUNTIMES='openmp' \
    -DCMAKE_INSTALL_PREFIX=./install \
    -DLLVM_OPTIMIZED_TABLEGEN=on \
    -DBUILD_SHARED_LIBS=on \
    -DLLVM_ENABLE_ASSERTIONS=${ASSERTIONS} \
    -DOPENMP_ENABLE_LIBOMPTARGET_PROFILING=off \
    -DLLVM_USE_LINKER=gold \
    -DLLVM_CCACHE_BUILD=off \
    -DLIBOMPTARGET_DEBUG=on \
    -DLIBOMPTARGET_ENABLE_DEBUG=On \
    ${CMAKEDIR}
